name: Tests

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Set up linters
      run: |
        go install golang.org/x/lint/golint
        go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow

    - name: Get dependencies
      run: |
        go mod download

    - name: Run linters
      run: |
        golint ./...
        go vet ./...
        go vet -vettool=$(which shadow) ./...
        go test -v -race ./...

    - name: Run tests
      run: |
        go test -v -race ./...
